Feature/upgrade libvirt qemu
isard-vdi/isard pull request #218
Opened 2020-08-27 20:04 UTC by jvinolas

This upgrades alpine base image to 3.12 and upgrades libvirt packages.
Some adjustments had to be done in the permissions to get libvirt+qemu working again as now libvirt wants a 'qemu' user to handle operations. This affects certificate permissions and host /dev/kvm mapped path.

2020-08-29 10:45 UTC, NefixEstrada requested changes

2020-08-29 10:45 UTC, NefixEstrada commented on engine/docker/Dockerfile
> +FROM alpine:latest as production
This should have the version locked

2020-08-30 18:04 UTC, alarraz approved these changes
Good job!! new libvirt version available

2020-08-30 18:10 UTC, NefixEstrada approved these changes

2020-08-31 07:05 UTC, merged