Feature/frontend persistents
isard-vdi/isard pull request #353
Opened 2020-12-18 16:19 UTC by jvinolas

This will get new endpoints on api and backend logic to handle persistent desktops

2020-12-19 08:16 UTC, sim6 requested changes
Endpoint /api/v2/desktops always says "type: persistent" and never shows the template.

2020-12-21 11:53 UTC, sim6 submitted a review, later dismissed
Now, the endpoint http://localhost:7039/api/v2/user/local-default-admin-admin/desktops always returns to me:
```
"type": "persistent", "template": ""
```
Also the endpoint https://localhost/api/v2/desktops remains like https://github.com/isard-vdi/isard/pull/353#pullrequestreview-555926259

2021-01-19 15:35 UTC, sim6 reviewed
Now the desktops list is fine. But I can start and stop desktops. I cannot found the isard-api endpoints for that.

2021-01-19 15:35 UTC, sim6 commented on backend/isard/desktop.go
> +	req, err := http.NewRequest(http.MethodGet, i.url("desktop/start/"+id), http.NoBody)
I cannot found this endpoint.

2021-01-19 15:35 UTC, sim6 commented on backend/isard/desktop.go
> +	req, err := http.NewRequest(http.MethodGet, i.url("desktop/stop/"+id), http.NoBody)
I cannot found this endpoint.

2021-02-03 10:37 UTC, NefixEstrada approved these changes

2021-02-05 09:24 UTC, merged

2021-02-05 10:43 UTC, fgonzalezmacias commented
Hello

This is a feature that will be great for me in my environment. I have updated and I see the change of look, what I do not see, is where I specify, that a user will be assigned a persistent desktop

![image](https://user-images.githubusercontent.com/72935746/107023230-9fe8d380-67a6-11eb-8994-184605539a7e.png)

Thanks in advance

2021-02-05 10:57 UTC, sim6 commented
We will document it but meanwhile...

Currently you only can start, open viewers and stop persistent desktops via simplified interface.
So you need first create it via full interface. Each user can create their persistent desktops or you as manager (or admin) could go to Manager (Administrator) / Desktops menu and click top right Bulk desktops button to create a persistent desktop for desired users.

2021-02-05 11:13 UTC, fgonzalezmacias commented
Ok, Thank you