allows multiple desktop creations
isard-vdi/isard pull request #354
Opened 2020-12-18 22:03 UTC by jvinolas

new 'bulk desktops' button created at domains page. It allows to create bulk desktops to individual users or users in categories, groups and roles.

2020-12-19 07:56 UTC, sim6 requested changes
I'm not inspected the code but it works for me. Please, adapt https://github.com/isard-vdi/isard/blob/develop/webapp/webapp/webapp/static/js/snippets/alloweds.js#L74 and https://github.com/isard-vdi/isard/blob/develop/webapp/webapp/webapp/static/js/snippets/alloweds.js#L104 to show a better placeholder for fields of "Users to create this desktop" form section.

2020-12-21 09:53 UTC, sim6 requested changes
Works for me. But:

1. Placeholder is not clear, see https://github.com/isard-vdi/isard/pull/354#pullrequestreview-555925341
2. As manager, the modal isn't closed after click Create desktop(s) button.
3. If there is any error, like the user have a desktop with the same name, no error is shown.
4. Please, squash commits.

2020-12-28 14:55 UTC, NefixEstrada approved these changes

2021-01-20 10:36 UTC, sim6 reviewed
Geat! It works for me, but please, could you remove the commented block?

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/admin/js/domains.js
> +            //~ setHardwareDomainDefaults('#modalAddDesktop',pk);
What about this comment?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/admin/js/domains.js
> +            $("#modalTemplateDesktop").modal('hide');
Could you remove the tailing whitespaces or not touch this line?
```suggestion
            $("#modalTemplateDesktop").modal('hide');
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/admin/js/domains.js
> +        });
Please, could you remove tailing whitespaces?
```suggestion
        });
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/js/snippets/desktop_add.js
> +            //~ "searching":         false,
What about this comment?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/js/snippets/desktop_add.js
> +				//~ },
Why not remove this comments?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/js/snippets/desktop_add.js
> +        //~ }
Why this commented block?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/admin/js/domains.js
> +        }else */
Why this commented block?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/js/snippets/desktop_add.js
> +        //~ });
What about this comments?
```suggestion
```

2021-01-20 10:36 UTC, sim6 commented on webapp/webapp/webapp/static/js/snippets/desktop_add.js
> +    //~ if(data.kind=="user_template"){return "private";}
What about this comments?
```suggestion
```

2021-01-20 15:25 UTC, sim6 approved these changes
Thanks!

2021-01-20 15:26 UTC, merged