First working version
isard-vdi/isard pull request #358
Opened 2020-12-23 13:13 UTC by jvinolas

It will allow to connect directly to the guest ip using wireguard client vpn. Things missing:
- Filter which guests ip the client can access, based on the guest ip assigned. We could get those by one of this options:
  - a) Get the dnsmasq assigned ip by quering qemu-ga (guest agent) when the host is up (i don't like this one)
  - b) Get the dnsmasq assigned ip querying libvirt (we should wait for guest to get ip)
  - c) Assign fixed IPs to libvirt dnsmasq. Here we could pre-generate this config based on MAC or try to modify the dnsmasq config and reload lively? Or maybe just do some kind of virsh net-edit using libvirt
    `cat /var/lib/libvirt/dnsmasq/wireguard.conf 
strict-order
pid-file=/var/run/libvirt/network/wireguard.pid
except-interface=lo
bind-dynamic
interface=virbr20
dhcp-range=192.168.128.33,192.168.129.254,255.255.252.0
dhcp-no-override
dhcp-authoritative
dhcp-lease-max=478
dhcp-hostsfile=/var/lib/libvirt/dnsmasq/wireguard.hostsfile
addn-hosts=/var/lib/libvirt/dnsmasq/wireguard.addnhosts
dhcp-option=121,10.200.200.0/24,192.168.128.1
`
- Discuss where to put the vpn configuration to be easy for clients. It is weird that it shows the button in viewers modal for each desktop as it will be the same config for the user always. Also we need to discuss how to give a simple access button for RDP using VPN
- Create a Windows client vbscript that checks if wireguard is installed, if not it downloads and installs and then applies the downloaded user vpn config and starts RDP with it's configuration

2020-12-24 06:07 UTC, sim6 requested changes
What about use `black` on new python files.

2020-12-24 06:07 UTC, sim6 commented on webapp/webapp/webapp/static/js/viewer.js
> +             }, */
What about remove commented code?

2020-12-24 06:07 UTC, sim6 commented on docker/vpn/src/wgtools.py
> +#AllowedIPs = 192.168.128.0/22, ::/0
What about remove this examples?
```suggestion
```

2020-12-28 08:27 UTC, jvinolas commented on docker-compose-parts/portal.yml
> +        target: 443
I'll take a look at black formatter...

2020-12-28 09:50 UTC, closed without merging