Optional adding custom networks
isard-vdi/isard pull request #386
Opened 2021-02-26 17:28 UTC by jvinolas

With this patch users can add their custom hypervisor networks at /opt/isard/networks in xml and it will be loaded and started at hypervisor restart.

2021-02-27 06:50 UTC, sim6 commented on docker-compose-parts/hypervisor.yml
> +      - /opt/isard/networks:/networks
What about use /opt/isard/hypervisor?
```suggestion
      - /opt/isard/hypervisor/networks:/networks
```

2021-03-01 13:06 UTC, sim6 requested changes
Nice! Could you squash the commits?

2021-03-03 07:32 UTC, jvinolas commented
Done

2021-03-03 09:32 UTC, sim6 requested changes
Should docker/hypervisor/custom-networks-add.py be included in isard-hypervisor image?

2021-03-10 18:02 UTC, jvinolas commented
Yes. We do include it but needs documentation.

2021-03-10 22:14 UTC, sim6 commented
So, do you forgot to add it via Dockerfile?

2021-03-18 11:08 UTC, sim6 requested changes
What about use /opt/isard/networks

2021-03-18 11:08 UTC, sim6 commented on docker-compose-parts/hypervisor.yml
> +      - /opt/isard/networks:/networks
What about use /opt/isard/hypervisor/networks instead of /opt/isard/networks?
```suggestion
      - /opt/isard/hypervisor/networks:/networks
```

2021-03-22 11:38 UTC, jvinolas commented
There is documentation on how to use custom networks in this document: https://docs.google.com/document/d/1ARfqYLJhd3vLeKmTS9bsth91N8FRA5z-6b-KYC7DLGI/edit
We should copy that to documentation.

2021-04-08 05:28 UTC, sim6 requested changes
Please, don't change the submodule `docker/static/noVNC/src`.

2021-09-27 12:51 UTC, closed without merging